import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,symlinkSync,existsSync,unlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,dirname} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {execFileSync,spawnSync} from 'node:child_process';
const scripts=resolve(process.argv[2] || join(dirname(fileURLToPath(import.meta.url)),'../skills/codex-quality-workflow/scripts'));
const {inspectDependencies,restoreDependencies,sourceFingerprint,dependencyFingerprint}=await import(pathToFileURL(join(scripts,'dependency-preflight.mjs')));
const temp=mkdtempSync(join(tmpdir(),'quality-deps-test-'));
const repo=join(temp,'repo with spaces');mkdirSync(repo);
const save=(path,data)=>{mkdirSync(dirname(path),{recursive:true});writeFileSync(path,typeof data==='string'?data:JSON.stringify(data));};
const git=(...args)=>execFileSync('git',['-C',repo,...args],{encoding:'utf8'}).trim();
git('init','-b','main');git('config','user.name','Test');git('config','user.email','test@example.invalid');
for (const nested of [false,true]) {
 const fixture=join(temp,nested?'nested-symlink':'root-symlink'),outside=join(temp,nested?'nested-outside':'root-outside');
 mkdirSync(fixture);mkdirSync(outside);
 save(join(fixture,'package.json'),{dependencies:{dep:'1.0.0'}});
 save(join(fixture,'package-lock.json'),{lockfileVersion:3,packages:{'':{dependencies:{dep:'1.0.0'}},'node_modules/dep':{version:'1.0.0'}}});
 save(join(outside,'dep/package.json'),{version:'1.0.0'});
 if(nested) {
  mkdirSync(join(fixture,'node_modules'));
  save(join(fixture,'node_modules/.package-lock.json'),{packages:{'node_modules/dep':{version:'1.0.0'}}});
  symlinkSync(join(outside,'dep'),join(fixture,'node_modules/dep'));
 } else {
  save(join(outside,'.package-lock.json'),{packages:{'node_modules/dep':{version:'1.0.0'}}});
  symlinkSync(outside,join(fixture,'node_modules'));
 }
 assert.equal(inspectDependencies(fixture).status,'BLOCKED_LOCKFILE');
}
save(join(repo,'.gitignore'),'node_modules/\n');
save(join(repo,'.claude/quality-workflow/validation.commands'),'node -e "console.log(1234567)"\n');
save(join(repo,'package.json'),{name:'test',workspaces:['packages/*'],dependencies:{dep:'1.0.0'}});
save(join(repo,'packages/lib/package.json'),{name:'@test/lib',version:'1.0.0'});
const lock={lockfileVersion:3,packages:{'':{workspaces:['packages/*'],dependencies:{dep:'1.0.0'}},'packages/lib':{name:'@test/lib',version:'1.0.0'},'node_modules/@test/lib':{resolved:'packages/lib',link:true},'node_modules/dep':{version:'1.0.0'},'node_modules/optional':{version:'1.0.0',optional:true}}};
save(join(repo,'package-lock.json'),lock);git('add','.');git('commit','-m','fixture');
const before=sourceFingerprint(repo),fingerprint=dependencyFingerprint(repo);
assert.equal(inspectDependencies(repo).status,'NEEDS_RESTORE');
assert.equal(sourceFingerprint(repo),before);
const bin=join(temp,'bin');mkdirSync(bin);
// Fake npm asserts immutable flags and supplies only ignored dependencies.
save(join(bin,'npm'),`#!${process.execPath}\nconst fs=require('fs');const a=process.argv.slice(2);if(!['ci','--ignore-scripts','--no-audit','--no-fund','--cache'].every(x=>a.includes(x)))process.exit(91);fs.mkdirSync('node_modules/@test',{recursive:true});fs.symlinkSync('../../packages/lib','node_modules/@test/lib');fs.mkdirSync('node_modules/dep',{recursive:true});fs.writeFileSync('node_modules/dep/package.json',JSON.stringify({version:'1.0.0'}));fs.writeFileSync('node_modules/.package-lock.json',JSON.stringify({packages:{'node_modules/dep':{version:'1.0.0'},'node_modules/@test/lib':{resolved:'packages/lib',link:true}}}));\n`);
execFileSync('chmod',['+x',join(bin,'npm')]);
const previousPath=process.env.PATH;process.env.PATH=bin+':'+previousPath;
const busy=join(repo,'.git/codex-quality-workflow/validation.lock');mkdirSync(busy,{recursive:true});
assert.equal(restoreDependencies(repo).status,'BUSY');
assert.ok(!existsSync(join(repo,'.git/claude-quality-workflow/validation.lock')));
execFileSync('rmdir',[busy]);
assert.equal(restoreDependencies(repo).status,'READY');
assert.equal(sourceFingerprint(repo),before);
assert.notEqual(dependencyFingerprint(repo),fingerprint);
assert.equal(inspectDependencies(repo).status,'READY');
const verify=(...args)=>spawnSync('bash',[join(scripts,'verify.sh'),'full',...args],{cwd:repo,encoding:'utf8'});
assert.equal(verify().status,0);
assert.match(verify('--reuse').stdout,/already passed/);
unlinkSync(join(repo,'package-lock.json'));
const unlocked=verify();
assert.equal(unlocked.status,78,'dependency-bearing projects without a supported lockfile must stop');
assert.ok(!unlocked.stdout.includes('1234567'),'no validation command ran before manual dependency preparation');
save(join(repo,'package-lock.json'),lock);
unlinkSync(join(repo,'node_modules/@test/lib'));
const staleCache=verify('--reuse');
assert.equal(staleCache.status,78,'preflight must block before cached validation reuse');
assert.ok(!staleCache.stdout.includes('1234567'),'no gate ran on a broken environment');
assert.equal(restoreDependencies(repo).status,'RESTORE_EXHAUSTED');
symlinkSync('../../packages/lib',join(repo,'node_modules/@test/lib'));
save(join(repo,'node_modules/dep/package.json'),{version:'2.0.0'});
assert.equal(inspectDependencies(repo).status,'NEEDS_RESTORE');
save(join(repo,'node_modules/dep/package.json'),{version:'1.0.0'});
save(join(repo,'package.json'),{name:'test',workspaces:['packages/*'],dependencies:{dep:'2.0.0'}});
assert.equal(inspectDependencies(repo).status,'BLOCKED_LOCKFILE');
assert.equal(restoreDependencies(repo).code,78);
assert.match(readFileSync(join(repo,'package-lock.json'),'utf8'),/1.0.0/);
save(join(repo,'package.json'),{name:'test',packageManager:'pnpm@10',dependencies:{dep:'1.0.0'}});
assert.equal(inspectDependencies(repo).status,'MANUAL_PREFLIGHT');
// A fresh fingerprint permits a new run, but installer source changes are detected.
save(join(repo,'package.json'),{name:'test',workspaces:['packages/*'],dependencies:{dep:'1.0.0'}});
save(join(repo,'new-source.txt'),'new state');
unlinkSync(join(repo,'node_modules/@test/lib'));
save(join(bin,'npm'),`#!${process.execPath}\nrequire('fs').writeFileSync('package.json','{}');process.exit(1);\n`);
assert.equal(restoreDependencies(repo).status,'SOURCE_CHANGED');
assert.equal(readFileSync(join(repo,'package.json'),'utf8'),'{}','never reset source to hide a mutation');
assert.ok(!existsSync(join(repo,'.git/codex-quality-workflow/validation.lock')));
save(join(repo,'package.json'),{name:'test',workspaces:['packages/*'],dependencies:{dep:'1.0.0'}});
save(join(repo,'node_modules/owned.txt'),'tracked user file');
git('add','-f','node_modules/owned.txt');
assert.equal(restoreDependencies(repo).status,'UNSAFE_TREE');
assert.equal(readFileSync(join(repo,'node_modules/owned.txt'),'utf8'),'tracked user file');
process.env.PATH=previousPath;
console.log('PASS dependency preflight: stale links, required versions, optional omission, immutable restore flags, source preservation/change detection, lock exclusion, bounded attempts, unsupported manager');
